### PR TITLE
Avatars: Don't draw background, neutral border with images

### PR DESCRIPTION
**Pull request by danrabbit**
Screenshot from 2020-10-02 17 10 45@2x

### CODE REVIEW

**Comment by Exalm** [comment]
Unrelated, but you only have 8 colors? `HdyAvatar` has 14, you need to specify all of them unless you want the remaining style classes to be unstyled. If you only want to use 8 colors, add some duplicates, like color9 == color1 etc.

**Comment by Exalm** [comment]
Screenshot from 2020-10-03 17-57-32

Here are names to reproduce all 14.

**Comment by fabiozaramella** [comment]
I can confirm that Hdy.Avatar widgets now looks as it should with this PR. However, 2 colors are missing/duplicate when tested using the above-mentioned names (see GIF attachment). Except this, everything is perfect. 👍🏼️

Peek 08-10-2020 10-41

**Review by fabiozaramella — APPROVED** [review]

**Comment by fabiozaramella** [comment]
I thinks that the new light blue and yellow/orange work really well 😍️. Good job!

**Pull request merged**
