### PR TITLE
Style keycaps in menus

### PR DESCRIPTION
**Pull request by danrabbit**
Screenshot from 2019-07-08 16 40 50@2x
Screenshot from 2019-07-08 16 43 16@2x

Passes WCAG AA

### CODE REVIEW

**Comment by peteruithoven** [comment]
I love that we're adding keyboard shortcuts to menu's but with this styling aren't the menu's going to be a bit to busy? Aren't we giving them to much visual priority?

**Comment by danrabbit** [comment]
@peteruithoven there's some conversation here for context: https://twitter.com/DanielFore/status/1148359052532969473

**Comment by peteruithoven** [comment]
Ah I see there are also more versions here: https://github.com/elementary/granite/pull/300

But what about not fulling the buttons with darker gray and using just a dark gray background? That way you could make the text a lighter (less visually prominent) gray as well. 

I don't see an easy way to quickly play with this myself.

**Comment by peteruithoven** [comment]
I'm thinking of larger menu's like the one in Files:
Screenshot from 2019-07-09 02 09 16@2x

**Comment by danrabbit** [comment]
Something I want to look at also is maybe making these shorter so that menu items are less grid-y and more row-y

**Comment by danrabbit** [comment]
Okay latest commit makes the light style much more subtle. Everything is adjusted to try to achieve the same level of contrast and remain accessible

Screenshot from 2019-07-09 08 02 52@2x
Screenshot from 2019-07-09 08 03 24@2x

**Comment by D0J0P** [comment]
Maybe someday when there's a "tablet mode" for tablets and 2-in-1s that has a removable keyboard, you can add the ability to remove all keycap shortcuts to clean it up and show only the available affordance.

**Comment by cassidyjames** [comment]
@D0J0P I was thinking about that! We should theoretically be able to check for attached input devices and only show them when there's a keyboard.

**Pull request merged**
