### PR TITLE
Fixes the padding on Gtk.FileChooserButton to be the same as Gtk.Entry

### LINKED ISSUE #400: Gtk.FileChooserButton paddings are inconsistent
Not exactly a big issue, but it would be nice if `Gtk.FileChooserButton` paddings were consistent with `Gtk.Entry`.

Here is a screenshot from my app:
padding

Note that first `Gtk.FileChooserButton` (with `.steam` folder selected) is in `Gtk.FileChooserAction.SELECT_FOLDER` mode and has correct paddings.

Second `Gtk.FileChooserButton` (with `start.sh` file selected) is in `Gtk.FileChooserAction.OPEN` mode.

---

Some of other GTK themes I've tried have consistent paddings.

Unfortunately some other themes like Adwaita have similar problems, but in most cases file icon is placed correctly and label has some extra padding, which can be reliably removed in app css without breaking other themes:
padding_adwaita

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63784747-gtk-filechooserbutton-paddings-are-inconsistent?utm_campaign=plugin&utm_content=tracker%2F45189256&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45189256&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by lainsce**
This makes Gtk.FileChooserButton follow the same margins the stylesheet does to Gtk.Entry, aligning both if used close together.
Fixes #400.

Looks like this:
Old =
screenshot from 2018-10-01 01 03 14

New = 
screenshot from 2018-10-01 01 03 42

### CODE REVIEW

**Comment by lainsce** [comment]
Oops, yeah, I forgot about the override thingy.

**Comment by lainsce** [comment]
Fixed~

**Comment by lainsce** [comment]
What happens with `master` is inconsistent padding due to no actual padding given to the icon in the button. With this PR, it actually stays consistent as is needed to fix the issue.

**Comment by lainsce** [comment]
Check this up, I changed some things (and added RTL too):
Red line shows the alignment.

screenshot from 2018-10-01 15-51-00

**Comment by danrabbit** [comment]
What the OP is showing is this, which you're not showing in your screenshot at all:

screenshot from 2018-10-01 12 57 12 2x

**Comment by lainsce** [comment]
It's the same widget as my screenshot's `(None)` widget as OP's `start.sh` & `.steam` widget. Now with this PR it is aligned properly. 🙂

**Comment by lainsce** [comment]
I'll take a picture of GameHub's prefs if it's needed.

**Comment by lainsce** [comment]
^ Thanks @danrabbit for helping me with a better way to do this :heart:

**Pull request merged**
