### PR TITLE
Add a workaround for GNOME apps using Gtk.Notebook

### LINKED ISSUE #211: Tabs' styles are inconsistent across the system
For instance, let us compare the tabs from Files to the tabs from Network Settings -> Advanced Settings. In Files, the tabs seem more modern and with correct borders (a very thin line at the top and a thin shadow at the bottom); but in Network Settings -> Advanced Settings there is no top border (it looks like a part of the tab is missing) and there is a **very** thick line at the bottom, which seems way off.

tabs

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/50079462-tabs-styles-are-inconsistent-across-the-system?utm_campaign=plugin&utm_content=tracker%2F45189256&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45189256&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #211 

Don't merge this, it could probably be made simpler

### CODE REVIEW

**Comment by dcominottim** [comment]
Please make it happen for Juno, guys!

**Comment by KeironO** [comment]
So, would I be right in saying that this resolves the theming issues on certain apps?

Ergo:

Epiphany error

**Comment by torikulhabib** [comment]
screenshot from 2018-08-05 06-31-30

**Comment by danrabbit** [comment]
This probably won't be merged because it's a huge hack

**Comment by ItsPossibleAlready** [comment]
OK ,if it won't merged,we need change gtk.notebook from switchboard to **Granite.DynamicNotebook** with `notebook.add_button_visible=false`

**Pull request closed without merging**
