### PR TITLE
New context menu design

### PR DESCRIPTION
**Pull request by lainsce**
| Light | Dark |
| :---: | :---: |
|light | dark|

### CODE REVIEW

**Comment by lainsce** [comment]
This has been long overdue honestly. I want the UX team to review this.

**Comment by cassidyjames** [comment]
I know the current separators are intentionally edge-to-edge. At a glance, this seems to do a lot to just add a lot of padding; what is the problem this PR is supposed to be solving?

**Comment by lainsce** [comment]
> Increased Spacing

While I do understand the reasoning for a compact menu, this can lead to unintentional clicks with less dexterous people. It's mainly an accessibility feature put into the defaults. It also makes things line up in the UI.

> Padded separators

A valid issue, will look into it.

> Accented highlight

This is to enable even more places for an app's branding to shine through.

> Spacing with icons

This was done intentionally so that icons line up visually instead of geometrically (which was bringing bugs to the table in certain menus)

> Dim labels

The PR was made before these were a thing. Valid point for me to look into.

**Comment by lainsce** [comment]
Review points should be addressed now. Separators are full-width again, and the accelerator key labels should be visible when selected.

**Comment by lainsce** [comment]
Last commit pulls some ideas from #582 to build upon my ideas above, merging both ideas.

**Comment by lainsce** [comment]
After last commit:

| Light | Dark |
| :---: | :---: |
|light | dark|

**Comment by danrabbit** [comment]
I'm inclined to close this since we're planning a larger rewrite of the stylesheet. I think I want to save any major style changes until then

**Pull request closed without merging**
