### PR TITLE
Make Entry and SpinButton Progess more subtle

### PR DESCRIPTION
**Pull request by danrabbit**
A little less obnoxious:

Screenshot from 2019-06-27 12 37 22@2x

### CODE REVIEW

**Comment by cassidyjames** [comment]
Hmm, I'm mixed. I think it makes sense to move it to the bottom, but this feels out of place. Would it be possible to do like a bottom glow of some sort? I'll try and look for an example of what I mean or mock something up.

**Comment by cassidyjames** [comment]
@danrabbit is something like this too subtle?

image

**Comment by danrabbit** [comment]
Hmm, maybe going the other direction? It seems to kind of conflict with the inset perspective of the entry

**Comment by cassidyjames** [comment]
@danrabbit hm, you lose the fuzziness on the edges which doesn't look quite as good, but I'm fine with the concept.

image

```css
    box-shadow: inset 0 -7px 3px -6px @colorAccent;
    margin: 0 -3px -4px;
```

…wait, we could probably do this with a background gradient.

**Comment by cassidyjames** [comment]
Background gradient style. Still not super happy with the sharp edges, though. But I think it's close.

image

Just remove the border and change the background-image to:

```css
    background-image: linear-gradient(alpha(@base_color, 0) 75%, @colorAccent);
```

**Comment by danrabbit** [comment]
Screenshot from 2019-06-27 14 43 51@2x

How about this?

**Comment by cassidyjames** [comment]
@danrabbit I'm not sure if the border radius on the gradient is better or worse than a hard edge. It looks a little out of place to me, though.

**Pull request merged**
