### PR TITLE
Fix heading label padding in lists

### LINKED ISSUE #1232: No padding on some headers
### What Happened?

image
image
image

### Steps to Reproduce

1. ???

### Expected Behavior

Padding as before

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes #1232

### CODE REVIEW

**Review by lenemter — APPROVED** [review]
Fixes the issue. Thanks

**Comment by lenemter** [comment]
Wait I didn't notice that header in switch button at the bottom:
image

**Comment by danirabbit** [comment]
@lenemter I think we should consider this a bug in the panel because it should add the `title-4` style class instead of using a headerlabel since it's not actually a header. That seems to fix it here:

Screenshot from 2022-10-06 15 57 05

**Comment by lenemter** [comment]
Makes sense. You can merge this PR then

**Pull request merged**
