### PR TITLE
reduce the height of the panel

### PR DESCRIPTION
**Pull request by danrabbit**

### CODE REVIEW

**Comment by cassidyjames** [comment]
Is this fixing a bug, or just a design change?

**Comment by lainsce** [comment]
@cassidyjames In a "franken-juno" install, wingpanel is using a little more space than usual. This is fixing this UI error. Unless I'm wrong about this PR.

**Comment by danrabbit** [comment]
Yeah that's it. Here's a screenshot of Loki. I'll double check that it's the same with this branch in just a second...

screenshot from 2017-09-27 14 59 19

**Comment by danrabbit** [comment]
Gonna merge because Juno cycle #YOLO

**Pull request merged**
