### PR TITLE
GTK4/Windows: dialog tweaks

### PR DESCRIPTION
**Pull request by danrabbit**
This makes dialogs nearly identical to how they were in GTK3

## GTK3
Screenshot from 2022-01-10 14 59 09

## GTK4
Screenshot from 2022-01-10 15 17 26

### CODE REVIEW

**Comment by cassidyjames** [comment]
@danrabbit it's possible I'm doing something terribly wrong, but… with or without this branch, I get funky shadow-less message dialogs.

**Comment by cassidyjames** [comment]
Ah I see there's a branch out against Granite that needs to be merged: https://github.com/elementary/granite/pull/546

**Comment by danrabbit** [comment]
@cassidyjames Yeah the branch for dialogs still hasn't been merged in granite so you need that still

**Review by cassidyjames — APPROVED** [review]
Style-wise this looks good to me, though!

**Pull request merged**
