### PR TITLE
Only apply border to SSD decoration

### PR DESCRIPTION
**Pull request by danrabbit**
Doesn't really fix the problem, but it is slightly better

## BEFORE
Screenshot from 2019-10-23 08 34 42@2x

## AFTER
Screenshot from 2019-10-23 08 35 20@2x

### CODE REVIEW

**Comment by micahilbery** [comment]
To me it looks like the after screenshot is about half as dark.

**Comment by danrabbit** [comment]
@Exalm zoom in an look at the top especially. It's a very subtle change, but it is lighter

**Comment by Exalm** [comment]
Ah, indeed, sorry. Still way too dark though, it still looks like double shadow to me. Maybe there's yet another place, because here's what the default shadow is supposed to look like:

Screenshot from 2019-10-23 20-57-12

**Comment by Exalm** [comment]
Huh, nevermind.

Screenshot from 2019-10-23 21-00-38

So that is the default shadow then, so the next step would be to tweak that to match the csd one.

**Pull request merged**
