### PR TITLE
attempt to fix scrollbar min sizes

### LINKED ISSUE #55: Scrollbars don't have a minimum size
This is the current scrollbar. It isnt there at all and its nearly impossible to click it - 1px grab. 

bildschirmfoto von 2017-01-23 12 28 10

The problem lies in my opinion on trough css definitions - they are not used in Adwaita. And we can now define slider-width with

```
slider {
    min-width: 2px;
}
```

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #55

### CODE REVIEW

**Comment by gwutz** [comment]
I think the pixelwidth is too big now.

peek 2017-01-23 22-01

**Comment by gwutz** [comment]
Yeah getting better. Hover state is still a little broad. And i think it should expand if we dont hover the slider right? And if i drag we should see the light background

peek 2017-01-23 22-13

**Comment by danrabbit** [comment]
That's the intended hover size.

Pushed another commit to try to address the hover states

**Comment by gwutz** [comment]
I think you got it :+1: 

peek 2017-01-23 22-20

**Comment by danrabbit** [comment]
Great! I requested a review from Sam for sanity check :)

**Comment by Philip-Scott** [comment]
@danrabbit min-width and min-height don't seem to exist on Gtk.3.18, and are causing warnings on all the programs that run:

```
(audience:15842): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2043:14: 'min-height' is not a valid property name

(audience:15842): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2044:13: 'min-width' is not a valid property name

(audience:15842): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2049:13: 'min-width' is not a valid property name
```

**Pull request merged**
