### PR TITLE
notebook tab:active is now notebook tab:checked

### LINKED ISSUE #58: [$15] Active Tab not shown
Tabs are not shown in Apps

Relevant Screenshot:

bildschirmfoto von 2017-01-23 21 06 55

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #58

### CODE REVIEW

**Comment by gwutz** [comment]
Active tab is shown now - but the styling issue is still there

peek 2017-01-23 22-32

**Comment by danrabbit** [comment]
Radius should be fixed, but might have to just deal with the double border

**Comment by gwutz** [comment]
Yeah and probably with the other directions

peek 2017-01-23 22-38

**Comment by danrabbit** [comment]
I already don't support those in master. New report :man_shrugging:

**Comment by cassidyjames** [comment]
Checked in GTK 3.24 and the tabs now have tab styles. :)

**Pull request merged**
