### PR TITLE
Improve Notebook styling

### PR DESCRIPTION
**Pull request by jepotter1-archive**
With light theme:

notebook-files

With dark theme:

notebook-code

Works with notebooks of all orientations (top, bottom, left & right):

gtk-widget-factory-notebook

### CODE REVIEW

**Comment by jwinnie** [comment]
Hmmm... I'm going to have to think about the design of this a bit more.

@elementary/ux design feedback/input needed

**Comment by jwinnie** [comment]
Okay, I've redesigned it to make it fit more with elementary's overall style, and also to improve on their sense of "physicality":

notebook-files

notebook-code

gtk-widget-factory-notebook

**Comment by hanaral** [comment]
I'm pretty sure this was an intentional change, and I feel that trying to rewrite something that was only recently done is not the right path. 
If you want to give connected tabs a shot I'd recommend on top of the sass Cassidy was experimenting with in this [branch](https://github.com/elementary/stylesheet/tree/notebook-traditional)

**Comment by jwinnie** [comment]
> I'm pretty sure this was an intentional change, and I feel that trying to rewrite something that was only recently done is not the right path.
> If you want to give connected tabs a shot I'd recommend on top of the sass Cassidy was experimenting with in this [branch](https://github.com/elementary/stylesheet/tree/notebook-traditional)

I tried that branch, but unfortunately it produces a bunch of weird visual artifacts and buginess when used with latest master, so I thought it would be easier just to write it from scratch.

**Comment by hanaral** [comment]
> I tried that branch, but unfortunately it produces a bunch of weird visual artifacts and buginess when used with latest master, so I thought it would be easier just to write it from scratch.

All you have to do is copy and paste the part that does the connected style on to the up to date sass.

**Pull request closed without merging**
