### PR TITLE
GTK4: Support `.keyboard-activating` class for buttons

### PR DESCRIPTION
**Pull request by lenemter**
See https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3390

I guess this class needs to be used in some other places, but this is bare minimum for https://github.com/elementary/calculator/pull/242

### CODE REVIEW

**Comment by BAProductions** [comment]
We need to see if other Ui Elements use .keyboard-activating  as well  & add it to the theme

**Comment by BAProductions** [comment]
> See https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3390
> 
> I guess this class needs to be used in some other places, but this is bare minimum for [elementary/calculator#242](https://github.com/elementary/calculator/pull/242)

We need to see if other UI Elements use .keyboard-activating as well & add it to the theme as needed.

**Comment by Exalm** [comment]
No, it's a GtkButton thing.

**Comment by lenemter** [comment]
Seems like more work needed to make this work with different styles. Converting to draft until issues resolved.

**Comment by lenemter** [comment]
> Seems like more work needed to make this work with different styles. Converting to draft until issues resolved.

The issue is in https://github.com/elementary/calculator/pull/242.

Ready for review.

**Comment by Exalm** [comment]
No, it doesn't. GTK3 just uses the :active state for that.

**Pull request merged**
