### PR TITLE
Ship indicator-less themes

### PR DESCRIPTION
**Pull request by lainsce**
This will be necessary to make the option of hiding indicators via the Appearance plug

### CODE REVIEW

**Comment by cassidyjames** [comment]
This won't work with the dark style switching, because Plank just looks for a `dock-dark.theme` file in response to the user preference.

**Comment by lainsce** [comment]
We just need to make it be smarter then, looking for the specific variant of Plank theming we want. It's easier than changing Plank code.

**Comment by cassidyjames** [comment]
Ah you're right. https://github.com/elementary/dock/pull/45

**Comment by lainsce** [comment]
Closing in favor of new logic on https://github.com/elementary/dock/pull/59

**Pull request closed without merging**
