### PR TITLE
Windows: Remove box shadow on .unified .flat.titlebar

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes a funny extra dark shadow line in the separators in Tasks (and other apps)

We don't need any box shadow at all here because the window border is set on the unified window and the inset highlight is done on the overlay node

### CODE REVIEW

**Comment by cassidyjames** [comment]
@danrabbit can you share a screenshot pointing out the difference here? I'm not seeing it. :mag:

**Comment by danrabbit** [comment]
Screenshot from 2020-11-03 09 32 56@2x

**Comment by danrabbit** [comment]
@cassidyjames actually this doesn't fix that thing. I don't know why I thought it did

**Review by cassidyjames — CHANGES_REQUESTED** [review]
Doesn't do the thing

**Pull request closed without merging**
