### PR TITLE
Slate Variant

### LINKED ISSUE #375: Add Slate Color Variant
We were talking in Slack about the possibility of generating and maintaining named color variants of the stylesheet, i.e. "elementary-slate", so eventually we could support picking a default accent color in the Desktop section of System Settings. We should be able to do this mostly programatically (and can even symlink most of the stylesheet back to the main version to save disk space, if we want).

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/62050260-add-slate-color-variant?utm_campaign=plugin&utm_content=tracker%2F45189256&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45189256&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by cassidyjames**
This moves the main stylesheet to an `elementary` subdirectory, and adds an `elementary-slate` directory next to it that is mostly symlinks to the main stylesheet, with just a different `gtk.css` and `gtk-dark.css` set of variables.

Fixes #375 

# Todo:

- [x] Draw back button assets
- [x] Figure out Plank badge (#545)

### CODE REVIEW

**Comment by terndrup** [comment]
Any update on getting this PR merged? I'm looking to create a navy-blue variant style so kinda waiting for the structure of this to finalise to have something more or less official to go by.

**Comment by micahilbery** [comment]
Afaik we're still blocked by plank and the way it shows notification badges.

**Comment by terndrup** [comment]
> 
> 
> Afaik we're still blocked by plank and the way it shows notification badges.

Ah I thought @cassidyjames had fixed that by just pushing a static base colour for the plank notifications. Imo the plank notifications don't have to follow the style variant for now.

**Comment by cassidyjames** [comment]
@terndrup the problem is that Plank badges automatically base themselves off of the GTK stylesheet's active color, no matter what. There is no facility to override that in Plank. So we're waiting on that feature in Plank itself.

**Comment by terndrup** [comment]
> 
> 
> @terndrup the problem is that Plank badges automatically base themselves off of the GTK stylesheet's active color, no matter what. There is no facility to override that in Plank. So we're waiting on that feature in Plank itself.

Ah I see! Sorry, I misunderstood the problem.

Time for us to fork Plank and do our own Elementary styled version? 👍

**Comment by cassidyjames** [comment]
@terndrup the Plank developers seem to be pretty receptive of features for elementary, so I think it'd be best to do the development upstream with a clear rationale.

**Comment by terndrup** [comment]
> @terndrup the Plank developers seem to be pretty receptive of features for elementary, so I think it'd be best to do the development upstream with a clear rationale.

@cassidyjames  Have you raised the issue with them? I'm happy to raise it too but maybe it will carry more weight coming from you, if they've catered to Elementary before I mean

**Comment by cassidyjames** [comment]
Now only blocked by #545

**Comment by lainsce** [comment]
^ not anymore :wink:

**Comment by danrabbit** [comment]
So I'm kind of feeling like maybe the most maintainable thing to do would be to add a build system to the stylesheet so that we can automatically generate the set of themes with different accents. I think we need to add a build system for sass anyways. Thoughts?

**Comment by lainsce** [comment]
I guess we should let the Slate PR merge first, then we make everything Sass, then we add other accents. This PR has some building blocks that are useful for the accent PRs to come.

**Comment by cassidyjames** [comment]
@danrabbit yeah I think a build system wouldn't hurt. Right now with one variant it's just a bunch of symlinks so it's very low maintenance burden, but I could see it becoming more confusing with more drastic changes to the set of stylesheets.

**Comment by danrabbit** [comment]
I'm going to close this since the plan is to have a build system in greenfield to generate accent color stylesheets

**Pull request closed without merging**
