### PR TITLE
Add undershoot to popovers

### PR DESCRIPTION
**Pull request by cassidyjames**
Undershoots help smooth out the edges of scrollable widgets. We opted to look at it on a widget-by-widget basis in #340, so here's the start of that for popovers.

## Before

Notice the hard edges on the user list.

Before

## After

Soft edges on the user list.

After

### CODE REVIEW

**Comment by cassidyjames** [comment]
Another place to look is the Wi-Fi menu in the network indicator

**Comment by peteruithoven** [comment]
@cassidyjames any change you could crop those images?

**Comment by lainsce** [comment]
I don't think cropping photos would solve the problem. Any type of image would be used as user photo, even logos.

**Comment by peteruithoven** [comment]
Sorry, to clarify I was refering to the screenshots, to make the examples easier to see. I wasn't suggesting an alternative solution.

**Comment by peteruithoven** [comment]
## Before
Before
## After
After

**Comment by cassidyjames** [comment]
A couple of more screenshots showing the change:

| Bottom cut off | Both ends cut off |
|---|---|
| wifi-1 | wifi-2 |

**Pull request merged**
